# Run many metamath verifiers on a set of metamath test files.
#
# If a metamath verifier simply returned "true" in all cases it would
# obviously not be a good verifier.  Here we provide a set of test files,
# load a number of metmath verifiers, and check if they accept what should
# be accepted and reject what should be rejected.
#
# For a list of verifiers see http://us.metamath.org/other.html#verifiers
#
language: rust
addons:
  apt:
    packages:
    - python3 # To run mmverify.py
    - darcs # To retrieve hmm
    - ghc   # Haskell compiler, to compile/run hmm
    - cabal-install # Haskell package manager, for hmm
python:
  - "3.5" # For mmverify.py
git:
  depth: 3
sudo: false
cache:
  cargo: true # Cache Rust source/executables (takes time to get and recompile)
  timeout: 3600 # Cache for 1 hour (unit is seconds)
before_install:
  - gcc --version
  - g++ --version
install:
  # Get *just* the metamath C program
  - wget -q -r -np -nd -A .c,.h http://us.metamath.org/metamath/
  # We would need these supporting files to check markup - don't bother.
  # - wget -q http://us.metamath.org/downloads/symbols.tar.bz2
  # - wget -q http://us.metamath.org/mpegif/mmset.html
  # - wget -q http://us.metamath.org/mpegif/mmhil.html
  # - wget -q http://us.metamath.org/mpegif/mmbiblio.html
  # - tar --strip-components=1 -jxf symbols.tar.bz2
  #
  # Compile metamath, a C verifier (and more) by Norm Megill.
  - gcc *.c -O2 -o metamath
  # Get mmj2, a Java verifier (and more) by Mel O'Cat and Mario Carneiro
  - wget -q http://us.metamath.org/ocat/mmj2/mmj2jar.zip
  - unzip -q mmj2jar.zip
  - printf "LoadFile,set.mm\nVerifyProof,*\nParse,*\nRunMacro,definitionCheck,ax-*,df-bi,df-clab,df-cleq,df-clel,df-sbc\n" > RunParms.txt
  - jdk_switcher use oraclejdk8
  # Install smetamath-rs (smm3), a Rust verifier by Stefan O'Rear
  # See: https://github.com/sorear/smetamath-rs
  - "[ -x  ~/.cargo/bin/smetamath ] || cargo install smetamath --vers 3.0.0"
  # Get and compile checkmm, a C++ verifier by Eric Schmidt
  - wget -q http://us.metamath.org/downloads/checkmm.cpp
  - g++ -O2 -o checkmm checkmm.cpp
  # Get mmverify.py, a Python verifier by Raph Levien
  - wget -q http://us.metamath.org/downloads/mmverify.py
  # Get and compile hmm, a Haskell verifier by Marnix Klooster
  - darcs get --tag=0.2 http://home.solcon.nl/mklooster/repos/hmm/
  - cabal update && cabal install parsec
  - cd hmm ; make hmmverify
script:
  - ./run-testsuite-all-drivers
